//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPRelayWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCPRelayWindow.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve host name.
        /// </summary>
        internal static string strCouldNotResolveHostName {
            get {
                return ResourceManager.GetString("strCouldNotResolveHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string strFailed {
            get {
                return ResourceManager.GetString("strFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start TCPRelay.
        /// </summary>
        internal static string strFailedToStartTCPRelay {
            get {
                return ResourceManager.GetString("strFailedToStartTCPRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Port.
        /// </summary>
        internal static string strListenPort {
            get {
                return ResourceManager.GetString("strListenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port TCPRelay will listen for connections.
        /// </summary>
        internal static string strListenPortHint {
            get {
                return ResourceManager.GetString("strListenPortHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string strLoading {
            get {
                return ResourceManager.GetString("strLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Twitch.tv servers.
        /// </summary>
        internal static string strLoadTwitchTVServers {
            get {
                return ResourceManager.GetString("strLoadTwitchTVServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve the list of servers from Twitch.tv and add them to the list.
        /// </summary>
        internal static string strLoadTwitchTVServersHint {
            get {
                return ResourceManager.GetString("strLoadTwitchTVServersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port {0} is already in use. Check if TCPRelay is already running or change the listen port..
        /// </summary>
        internal static string strPortAlreadyInUse {
            get {
                return ResourceManager.GetString("strPortAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port {0} is already in use by {1} (PID: {2}). Change the listen port or try closing the application or modifying its settings..
        /// </summary>
        internal static string strPortAlreadyInUseByProcess {
            get {
                return ResourceManager.GetString("strPortAlreadyInUseByProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string strStart {
            get {
                return ResourceManager.GetString("strStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string strStarted {
            get {
                return ResourceManager.GetString("strStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string strStarting {
            get {
                return ResourceManager.GetString("strStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the relay.
        /// </summary>
        internal static string strStartsTheRelay {
            get {
                return ResourceManager.GetString("strStartsTheRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string strStop {
            get {
                return ResourceManager.GetString("strStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string strStopped {
            get {
                return ResourceManager.GetString("strStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string strStopping {
            get {
                return ResourceManager.GetString("strStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the relay.
        /// </summary>
        internal static string strStopsTheRelay {
            get {
                return ResourceManager.GetString("strStopsTheRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target URI.
        /// </summary>
        internal static string strTargetURI {
            get {
                return ResourceManager.GetString("strTargetURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepts the following format:
        ///[&lt;protocol&gt;://]&lt;host&gt;[:&lt;port&gt;][/&lt;path&gt;]
        ///[...] denote optional parts.
        /// </summary>
        internal static string strTargetURIHint {
            get {
                return ResourceManager.GetString("strTargetURIHint", resourceCulture);
            }
        }
    }
}
