//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPRelayControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCPRelayControls.ControlsStrings", typeof(ControlsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all closed connections.
        /// </summary>
        internal static string strClearAllClosedConnections {
            get {
                return ResourceManager.GetString("strClearAllClosedConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string strClosed {
            get {
                return ResourceManager.GetString("strClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string strConnecting {
            get {
                return ResourceManager.GetString("strConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}....
        /// </summary>
        internal static string strConnectingTo {
            get {
                return ResourceManager.GetString("strConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string strConnections {
            get {
                return ResourceManager.GetString("strConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed: {0} updates per second.
        /// </summary>
        internal static string strCurrentSpeed {
            get {
                return ResourceManager.GetString("strCurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1}.
        /// </summary>
        internal static string strFromXToY {
            get {
                return ResourceManager.GetString("strFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound.
        /// </summary>
        internal static string strInbound {
            get {
                return ResourceManager.GetString("strInbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound.
        /// </summary>
        internal static string strOutbound {
            get {
                return ResourceManager.GetString("strOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string strSpeed {
            get {
                return ResourceManager.GetString("strSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred.
        /// </summary>
        internal static string strTransferred {
            get {
                return ResourceManager.GetString("strTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase update speed.
        /// </summary>
        internal static string strUpdateFaster {
            get {
                return ResourceManager.GetString("strUpdateFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update as fast as possible.
        /// </summary>
        internal static string strUpdateFastest {
            get {
                return ResourceManager.GetString("strUpdateFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease update speed.
        /// </summary>
        internal static string strUpdateSlower {
            get {
                return ResourceManager.GetString("strUpdateSlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update as slow as possible.
        /// </summary>
        internal static string strUpdateSlowest {
            get {
                return ResourceManager.GetString("strUpdateSlowest", resourceCulture);
            }
        }
    }
}
